### ISSUE TITLE
Has the current tool chain ever incorrectly paritioned when it should not have?

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNGym#6]
@andrewgait Explained that the ApplicationVeretexes have been modiifed so that get_resources_used_by_atoms methods lies about the resources required to guarantee that there is only ever 1 MachineVertex

I fully understand that is currently the only way to guarantee a single MachineVertex .

My question:
Is anyone aware of a case where the partitioner actually did split into multiple MachineVertexes where in fact with the above change it ran on a single one.

This is not to critise the approach here but to identify if there are cases where the paritioner has made an incorrect assumption that it needed to use multiple cores.

**Comment by andrewgait** [comment]
I think with the recent merge and the use of AbstractOneAppOneMachineVertex this question has been resolved.
