### ISSUE TITLE
Create some proper testing for current examples

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/SpiNNGym#7]
Now that this repository is up to date with current master, soon will be a good time to create some proper (integration) testing for the current examples.

**Comment by Christian-B** [comment]
Fixed in https://github.com/SpiNNakerManchester/SpiNNGym/pull/17

**Comment by Christian-B** [comment]
I was under the understanding that @andrewgait wants to do more than just run the scripts.
Actually checking the results

And that was the reason for this Issue.

If that is no longer planned feel free to close again.

**Comment by andrewgait** [comment]
@Christian-B is right - let's leave this open until I write some results checking for this repository.

**Comment by andrewgait** [comment]
I didn't get round to any further results checking in this repository.  I suggest closing this and if anyone picks up this repository in the future, especially if they add further binaries, then they can improve the testing.
